---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-registry
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.27.11.40
    path: /srv/nfs/v0
--
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
